version: '3'
services:
  deployed_app:
    container_name: backend_deployed
    build: ./server/.
    environment:
      - HPORT=5010
    links:
      - mongo_sample
    ports:
      - 5010:5000  
    depends_on:
      - mongo_sample
  
  
  mongo_sample:
    container_name: database_deployed
    image: mongo
    ports:
      - 27012:27017

